name: kino_app
description: Kino app by Abbos Donaboyev

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  dio: ^5.8.0+1
  intl: ^0.20.2
  alice: ^0.4.2
  equatable: ^2.0.7
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  carousel_slider: ^5.0.0
  freezed_annotation: ^3.0.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  retrofit_generator: ^9.2.0
  flutter_launcher_icons: ^0.14.3
  freezed: ^3.0.6

flutter_launcher_icons:
  android: true
  image_path: 'assets/images/png/kino_app_logo.png'

flutter:
  uses-material-design: true
  fonts:
    - family: Amatic
      fonts:
        - asset: assets/fonts/AmaticSC-Bold.ttf
    - family: Marker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf

  assets:
    - assets/fonts/
    - assets/images/png/

    - .env